INSERT INTO TBL_CUSTOMER (CUSTOMER_REF, CUSTOMER_NAME, ADDRESS_LINE1, ADDRESS_LINE2, TOWN, COUNTY, COUNTRY, POSTCODE) VALUES
  ('CS1', 'Peter', '22', 'Willow Close', 'Hinckley', 'Leicestershire', 'UK', 'LE10 2JY');
